spring:
  application:
    name: notification-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5437/notification_db?TimeZone=Asia/Ho_Chi_Minh}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: false

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:notification-service-group}
      auto-offset-reset: earliest
      enable-auto-commit: false

app:
  kafka:
    topics:
      payment:
        succeeded: ${KAFKA_TOPIC_PAYMENT_SUCCEEDED:payment.succeeded}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${SERVER_PORT:8086}

rest:
  api:
    user-service:
      baseUrl: ${USER_SERVICE_URL:http://localhost:8081}

api-key:
  value: ${API_KEY}