server:
  port: ${SERVER_PORT:8082}

spring:
  application:
    name: pet-service
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/pet_db}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000 

  jpa:
    hibernate:
      ddl-auto: none 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

  liquibase:
    enabled: true
    changelog: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    drop-first: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8088/realms/petstore/protocol/openid-connect/certs}
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8088/realms/petstore}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: pet-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8088}
  realm: ${KEYCLOAK_REALM:petstore}
  client-id: ${KEYCLOAK_CLIENT_ID:spring-boot-api}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:Ji9NSOcVjSUul7finhrE5dGuLZuVSagV}

logging:
  level:
    com.petstore.petservice: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    liquibase: DEBUG
    liquibase.changelog: DEBUG
    liquibase.database: DEBUG