spring:
  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 60000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  application:
    name: order-service
  
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8088/realms/super-petmark-3d/protocol/openid-connect/certs}

  config:
    import:
      - classpath:kafka-config.yml
      - classpath:redisson-config.yml

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/order_db?TimeZone=Asia/Ho_Chi_Minh}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  liquibase:
    enabled: true
    changelog: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    drop-first: false

server:
  port: ${SERVER_PORT:8084}

rest:
    api:
        user-service:
            baseUrl: ${USER_SERVICE_URL:http://localhost:8081}
        pet-service:
            baseUrl: ${PET_SERVICE_URL:http://localhost:8082}
        payment-service:
            baseUrl: ${PAYMENT_SERVICE_URL:http://localhost:8085}

api:
  key: ${API_KEY}
