import { Category } from '../types';

export const STORE_CATEGORIES: Category[] = [
  {
    id: 'cat-thu-cung',
    name: 'Thú Cưng',
    slug: 'thu-cung',
    count: '19+ bé thuần chủng',
    description: 'Chó cảnh, mèo cảnh thuần chủng tuyển chọn, bảo hành sức khỏe & sổ tiêm đầy đủ',
    icon: 'Dog',
    bgColor: 'bg-[#FBECE6] hover:bg-[#F8DEC5]',
    accentColor: '#E65C38',
    image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-thuc-an',
    name: 'Thức Ăn',
    slug: 'thuc-an',
    count: '10+ sản phẩm',
    description: 'Hạt dinh dưỡng cao cấp, pate thơm ngon, súp thưởng và snack sạch',
    icon: 'Utensils',
    bgColor: 'bg-[#F4F1EA] hover:bg-[#EAE4D7]',
    accentColor: '#8C7A60',
    image: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-quan-ao',
    name: 'Quần Áo',
    slug: 'quan-ao',
    count: '5+ mẫu thiết kế',
    description: 'Áo len dệt kim ấm áp, áo mưa chống thấm, yếm thời trang công thái học',
    icon: 'Sparkles',
    bgColor: 'bg-[#F2EEF9] hover:bg-[#E5DDF5]',
    accentColor: '#7A62A8',
    image: 'https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-nha-chuong',
    name: 'Nhà / Chuồng',
    slug: 'nha-chuong',
    count: '6+ mẫu decor',
    description: 'Nhà gỗ tối giản, chuồng quây gấp gọn thông minh, nệm mây memory foam',
    icon: 'Home',
    bgColor: 'bg-[#F7F2EB] hover:bg-[#EEE5D8]',
    accentColor: '#A68256',
    image: 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'cat-phu-kien',
    name: 'Phụ Kiện',
    slug: 'phu-kien',
    count: '18+ phụ kiện',
    description: 'Vòng cổ tích hợp AirTag, dây dắt trợ lực rảnh tay, bát sứ công thái học & đồ chơi',
    icon: 'Package',
    bgColor: 'bg-[#EBF3ED] hover:bg-[#DCECE0]',
    accentColor: '#4A7C59',
    image: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=600&auto=format&fit=crop&q=80',
  },
];
